Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2021-07, with the labels that each got.

#417 RELEASE.md: update with gcr promotion guidelines
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 Default images to the official k8s.gcr.io and gcr.io registries
  Makefile
  deploy/README.md
  deploy/manifests/custom-metrics-apiserver-deployment.yaml
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#418 Remove travis in favor of prow.k8s.io
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#421 Fix external rule tag in documentation
  docs/externalmetrics.md
  docs/sample-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#420 Stop populating IMAGE env variable
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#423 Fix push-multi-arch image deployment
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#424 Increase cloudbuild timeout to 1h
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#435 fix: incorrect type used for openapi spec
  cmd/adapter/adapter.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#434 Document image registries
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#431 Prevent prometheus-adapter from returning negative resource metrics
  pkg/resourceprovider/provider.go
  pkg/resourceprovider/provider_test.go
Labels: approved, cncf-cla: yes, size/M

#432 Support setting headers on requests to Prometheus
  cmd/adapter/adapter.go
  cmd/adapter/adapter_test.go
  pkg/client/api.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#436 fix: add openapi spec for custom and external metrics types
  cmd/adapter/adapter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
