Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2021-03, with the labels that each got.

#319 Update Prometheus Operator Doc location
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm

#354 add TLS auth for accessing Prometheus
  cmd/adapter/adapter.go
  cmd/adapter/adapter_test.go
  cmd/adapter/testdata/ca-error.pem
  cmd/adapter/testdata/ca.pem
  cmd/adapter/testdata/kubeconfig
  cmd/adapter/testdata/kubeconfig-error
  cmd/adapter/testdata/tlscert-error.crt
  cmd/adapter/testdata/tlscert.crt
  cmd/adapter/testdata/tlskey.key
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#372 pkg/config: allow configuration to be read from json schema
  pkg/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#379 fix walkthrough example
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#384 OWNERS: Remove myself from the OWNERS
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#386 Fix documented metrics labels to work for k8s 1.16+
  cmd/config-gen/utils/default.go
  deploy/manifests/custom-metrics-config-map.yaml
  docs/config.md
  docs/sample-config.yaml
  pkg/custom-provider/provider_test.go
  pkg/custom-provider/series_registry_test.go
  pkg/resourceprovider/provider_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#382 Makefile: include tests from cmd directory
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#387 .travis.yml: remove verify job
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#389 Add signal handler
  cmd/adapter/adapter.go
Labels: approved, cncf-cla: yes, lgtm, size/S
