Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2021-08, with the labels that each got.

#440 Remove unused travis deploy file
  .travis-deploy.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#443 Update golang dependencies
  cmd/adapter/adapter.go
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/custom-provider/provider.go
  pkg/custom-provider/provider_test.go
  pkg/custom-provider/series_registry.go
  pkg/custom-provider/series_registry_test.go
  pkg/external-provider/external_series_registry.go
  pkg/external-provider/metric_converter.go
  pkg/external-provider/provider.go
  pkg/naming/resource_converter.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#444 Propagate metric providers context
  pkg/custom-provider/provider.go
  pkg/external-provider/provider.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#442 Update documentation to include metrics-max-age
  README.md
Labels: cncf-cla: yes, lgtm, size/S, ok-to-test, approved

#448 v0.9.0: Bump version file to reflect new release
  VERSION
Labels: cncf-cla: yes, lgtm, size/XS, ok-to-test, approved

#447 README: improve gcr.k8s.io instructions
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved
