Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2021-06, with the labels that each got.

#399 go.mod: bump dependencies
  cmd/adapter/adapter.go
  go.mod
  go.sum
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/resourceprovider/provider.go
  pkg/resourceprovider/provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#395 Prevent metrics-server panics on GetContainerMetrics and GetNodeMetrics
  pkg/resourceprovider/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#404 Move prometheus-adapter to sigs.k8s.io golang package
  Makefile
  cmd/adapter/adapter.go
  cmd/config-gen/main.go
  cmd/config-gen/utils/default.go
  go.mod
  pkg/client/fake/client.go
  pkg/client/metrics/metrics.go
  pkg/custom-provider/provider.go
  pkg/custom-provider/provider_test.go
  pkg/custom-provider/series_registry.go
  pkg/custom-provider/series_registry_test.go
  pkg/external-provider/basic_metric_lister.go
  pkg/external-provider/external_series_registry.go
  pkg/external-provider/metric_converter.go
  pkg/external-provider/periodic_metric_lister_test.go
  pkg/external-provider/provider.go
  pkg/naming/metric_namer.go
  pkg/naming/metrics_query.go
  pkg/naming/metrics_query_test.go
  pkg/naming/regex_matcher_test.go
  pkg/naming/resource_converter.go
  pkg/resourceprovider/provider.go
  pkg/resourceprovider/provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#405 Filter non-running pods
  cmd/adapter/adapter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#406 Makefile: consolidate docker-build
  .gitignore
  Dockerfile
  Makefile
  deploy/Dockerfile
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#408 *: add version file
  .travis-deploy.sh
  Makefile
  VERSION
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#407 Remove localvendor directory
  go.mod
  localvendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/go.mod
  localvendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#410 Fix pod lister by running the pod informer
  .travis.yml
  cmd/adapter/adapter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#415 Improve container push rules
  .travis-deploy.sh
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#416 Add cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
