Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2022-12, with the labels that each got.

#547 Fix GO-2022-0969
  go.mod
  go.sum
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, needs-triage, approved

#546 Refactor adding logging flags
  cmd/adapter/adapter.go
  cmd/adapter/adapter_test.go
Labels: cncf-cla: yes, kind/cleanup, size/M, lgtm, needs-triage, approved

#550 golangci-lint: Add stylecheck linter
  .golangci.yml
  pkg/resourceprovider/provider.go
Labels: cncf-cla: yes, lgtm, size/S, needs-triage, approved

#518 Fix broken links in README.md
  README.md
Labels: cncf-cla: yes, triage/accepted, lgtm, size/XS, ok-to-test, approved

#551 Bump golang.org/x/net to v0.4.0 for GO-2022-1144
  go.mod
  go.sum
Labels: cncf-cla: yes, triage/accepted, lgtm, size/XS, approved
