Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2022-08, with the labels that each got.

#521 Update dependencies
  Makefile
  cmd/adapter/adapter.go
  go.mod
  go.sum
  hack/tools.go
  pkg/api/generated/openapi/zz_generated.openapi.go
  pkg/api/openapi-gen.go
  pkg/resourceprovider/provider.go
  pkg/resourceprovider/provider_test.go
Labels: cncf-cla: yes, size/XXL, approved

#509 Add --prometheus-verb to support POST requests to prometheus servers
  cmd/adapter/adapter.go
  pkg/client/api.go
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#523 Cut release 0.10.0
  VERSION
Labels: cncf-cla: yes, size/XS, approved

#524 cmd/adapter: recover klog flags
  cmd/adapter/adapter.go
Labels: cncf-cla: yes, size/XS, approved

#528 Fix image location in manifests
  deploy/manifests/custom-metrics-apiserver-deployment.yaml
Labels: cncf-cla: yes, size/XS, approved

#526 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#529 Update registry location to registry.k8s.io
  README.md
  deploy/manifests/custom-metrics-apiserver-deployment.yaml
  docs/walkthrough.md
Labels: cncf-cla: yes, size/XS, approved
