Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2022-11, with the labels that each got.

#531 Updates deploy/manifest to latest version in sync with kube-prom
  README.md
  deploy/README.md
  deploy/manifests/api-service.yaml
  deploy/manifests/cluster-role-aggregated-metrics-reader.yaml
  deploy/manifests/cluster-role-binding-delegator.yaml
  deploy/manifests/cluster-role-binding-hpa-custom-metrics.yaml
  deploy/manifests/cluster-role-binding.yaml
  deploy/manifests/cluster-role-metrics-server-resources.yaml
  deploy/manifests/cluster-role.yaml
  deploy/manifests/config-map.yaml
  deploy/manifests/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml
  deploy/manifests/custom-metrics-apiserver-deployment.yaml
  deploy/manifests/custom-metrics-apiserver-resource-reader-cluster-role-binding.yaml
  deploy/manifests/custom-metrics-apiserver-service-account.yaml
  deploy/manifests/custom-metrics-apiserver-service.yaml
  deploy/manifests/custom-metrics-apiservice.yaml
  deploy/manifests/custom-metrics-cluster-role.yaml
  deploy/manifests/custom-metrics-config-map.yaml
  deploy/manifests/custom-metrics-resource-reader-cluster-role.yaml
  deploy/manifests/deployment.yaml
  deploy/manifests/network-policy.yaml
  deploy/manifests/pod-disruption-budget.yaml
  deploy/manifests/role-binding-auth-reader.yaml
  deploy/manifests/service-account.yaml
  deploy/manifests/service.yaml
  docs/walkthrough.md
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved

#538 Fix segfault when using --prometheus-token-file
  cmd/adapter/adapter.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#542 Add olivierlemasle as reviewer
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/S, approved

#540 Use golangci-lint
  .golangci.yml
  Makefile
  cmd/adapter/adapter.go
  cmd/adapter/adapter_test.go
  cmd/config-gen/utils/default.go
  hack/gofmt-all.sh
  pkg/client/api.go
  pkg/client/helpers.go
  pkg/client/interfaces.go
  pkg/client/metrics/metrics.go
  pkg/client/types.go
  pkg/config/loader.go
  pkg/custom-provider/provider.go
  pkg/custom-provider/provider_test.go
  pkg/custom-provider/series_registry_test.go
  pkg/external-provider/basic_metric_lister.go
  pkg/external-provider/external_series_registry.go
  pkg/external-provider/metric_converter.go
  pkg/external-provider/periodic_metric_lister.go
  pkg/naming/lbl_res.go
  pkg/naming/metric_namer.go
  pkg/naming/metrics_query.go
  pkg/resourceprovider/provider.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#544 Set MinVersion: tls.VersionTLS12 in prometheus client's TLSClientConfig
  cmd/adapter/adapter.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
