Repository kubernetes-sigs/prometheus-adapter, pull requests merged in 2023-01, with the labels that each got.

#553 Patch upgrade of Golang to 1.18.9
  Makefile
Labels: cncf-cla: yes, triage/accepted, lgtm, size/XS, ok-to-test, approved

#539 Add initial e2e tests
  .gitignore
  Makefile
  deploy/manifests/config-map.yaml
  go.mod
  go.sum
  test/README.md
  test/e2e/e2e_test.go
  test/prometheus-manifests/cluster-role-binding.yaml
  test/prometheus-manifests/cluster-role.yaml
  test/prometheus-manifests/prometheus.yaml
  test/prometheus-manifests/service-account.yaml
  test/prometheus-manifests/service-monitor-kubelet.yaml
  test/prometheus-manifests/service.yaml
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/XL, lgtm, approved

#559 Fix yaml in sample config & docs
  docs/config.md
  docs/sample-config.yaml
Labels: cncf-cla: yes, triage/accepted, lgtm, size/S, kind/documentation, ok-to-test, approved
